name: Docker


on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - 'docker/**'
      - '!docker/Dockerfile'
      - '.github/**'
      - '!.github/workflows/docker.yml'
      - 'LICENSE-*'
  workflow_dispatch:


jobs:
  build-and-push:
    name: Build and Push
    uses: codex-storage/github-actions/.github/workflows/docker-reusable.yml@master
    with:
      docker_file: docker/Dockerfile
      dockerhub_repo: codexstorage/codex-marketplace-ui
      build_args: |
        VITE_CODEX_API_URL=${VITE_CODEX_API_URL}
        VITE_GEO_IP_URL=${VITE_GEO_IP_URL}
      tag_latest: ${{ github.ref_name == github.event.repository.default_branch || startsWith(github.ref, 'refs/tags/') }}
    secrets: inherit
